name: Build Blender Add-on

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Blender
        uses: bradyajohnston/setup-blender@v3
        with:
          version: "4.5"  # replace with the exact Blender version you want

      - name: Run Blender build command
        run: |
          mkdir -p builds
          blender --command extension build --source-dir . --output-dir builds/ --verbose

